name: CI
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: 1.25
          cache: true

      - run: |
          make test
          make vet

      - uses: goreleaser/goreleaser-action@v6
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
