name: CI
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    paths-ignore: 
      - '*.md'
      - '*.txt'
      - '*.yml'
      - '*.yaml'
    branches:
      - main

permissions:
  contents: write
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: 1.25
          cache: true

      - run: |
          make test
          make vet

      - name: tag release
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=$(go run . --version)
          
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping release"
          else
            echo "Creating new tag and release for $TAG"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git tag "$TAG"
            git push origin "$TAG"
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: create release 
        uses: goreleaser/goreleaser-action@v6
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
